// Auto-generated by scripts/optimize-images.mjs
// Do not edit manually

export interface ProjectImage {
  filename: string;
  full: string;
  thumb: string;
  blurDataURL: string;
  width: number;
  height: number;
}

export interface ProjectVideo {
  filename: string;
  src: string;
}

export interface Project {
  id: string;
  images: ProjectImage[];
  videos: ProjectVideo[];
}

export const projects: Project[] = [
  {
    id: "project-1",
    images: [
          {
                "filename": "img-001.webp",
                "full": "/images/projects/project-1/full/img-001.webp",
                "thumb": "/images/projects/project-1/thumb/img-001.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACQAQCdASoKAA0ABUB8JQBOgBsshkAA/qMpLiFZZUocuWSBl2ZcT5QVELPAodOishIif43k21AmXmvwXa4AAA==",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-002.webp",
                "full": "/images/projects/project-1/full/img-002.webp",
                "thumb": "/images/projects/project-1/thumb/img-002.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZQAAqrvaAD2ov2MSzh/GHci+GqwC3S5h4CPCdgDegAA",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-003.webp",
                "full": "/images/projects/project-1/full/img-003.webp",
                "thumb": "/images/projects/project-1/thumb/img-003.webp",
                "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoKAA0ABUB8JbACdAEDlJTyAAD2Q7Lp7aVm6F0wfR/4gSJz5NM1YiGAi15IuYPEOwEMmGLmAzCifxtEUv2bpAAA",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-004.webp",
                "full": "/images/projects/project-1/full/img-004.webp",
                "thumb": "/images/projects/project-1/thumb/img-004.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACQAQCdASoKAAgABUB8JZQAApwMCAAA/LSlVqqjE4YC2AC/8lruhM0yiBAAAA==",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-005.webp",
                "full": "/images/projects/project-1/full/img-005.webp",
                "thumb": "/images/projects/project-1/thumb/img-005.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoKAA0ABUB8JYwC7AEWPJNSwAD42/EUCuK1wWsQdEhgFzxxNTZ097zHI9uEg4IGJQjoh0Ix1vnbgAAA",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-006.webp",
                "full": "/images/projects/project-1/full/img-006.webp",
                "thumb": "/images/projects/project-1/thumb/img-006.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoKAA0ABUB8JQBOgBuUX6jjcAAA/t2SvuF2lRU1NF9aHeowOV85N5D/GNYJb+ei+HnuYJh+AAA=",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-007.webp",
                "full": "/images/projects/project-1/full/img-007.webp",
                "thumb": "/images/projects/project-1/thumb/img-007.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoKAA0ABUB8JZQC7AD5WpP0AAAA/rQGYLk8pv41G+vE1Ug6RdjwxjP6qY0AKB+LJKO9AVV8+FpWAAAA",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-008.webp",
                "full": "/images/projects/project-1/full/img-008.webp",
                "thumb": "/images/projects/project-1/thumb/img-008.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAAAQAgCdASoKAA0ABUB8JQBdgCKxmBbtK94AAPyPYWYrI17dK2P2iafHLryPjhJkgzrJpAAA",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-009.webp",
                "full": "/images/projects/project-1/full/img-009.webp",
                "thumb": "/images/projects/project-1/thumb/img-009.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoKAA0ABUB8JQBdgBunnJefwAD98EnBHf+KRJLH29Cr7ON9B+i/BmasIAA=",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-010.webp",
                "full": "/images/projects/project-1/full/img-010.webp",
                "thumb": "/images/projects/project-1/thumb/img-010.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoKAA0ABUB8JYwAAlzxdIwAAMshCq2sdSPOLaOWS/VVeaRjSlEYX0Vb+n1zYYl4HUfikHkXoGnPgAAA",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-011.webp",
                "full": "/images/projects/project-1/full/img-011.webp",
                "thumb": "/images/projects/project-1/thumb/img-011.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoKAA0ABUB8JZQAAq7zrFt5gAD+lEb+T7BmD4D2zy7uBq9kZPS5UPZThIF4yxOAqhGzVWcCAAA=",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-012.webp",
                "full": "/images/projects/project-1/full/img-012.webp",
                "thumb": "/images/projects/project-1/thumb/img-012.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACQAQCdASoKAA0ABUB8JZQAAkrXyEAA+8jwJHaQxNYd063W25CZfoJFdW2zxev4zHlXtJho0gIAAA==",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-013.webp",
                "full": "/images/projects/project-1/full/img-013.webp",
                "thumb": "/images/projects/project-1/thumb/img-013.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAABQAQCdASoKAA0ABUB8JZQAAOEAAM3uJXi2bwYZTjqQ32cSTnpQ9pl3+VZPa1uHgOiy8AAA",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-014.webp",
                "full": "/images/projects/project-1/full/img-014.webp",
                "thumb": "/images/projects/project-1/thumb/img-014.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAAAQAgCdASoKAAgABUB8JZACdADp5V9AasQAAPE5hdT4oF6jFUUY/k6j3eJq1wiuRtIH7sYjqjAAAA==",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-015.webp",
                "full": "/images/projects/project-1/full/img-015.webp",
                "thumb": "/images/projects/project-1/thumb/img-015.webp",
                "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAABwAQCdASoKAA0ABUB8JZwAAkyMAADzx5YF4ucVBf6i0TPe+jJ1qPKaQUNqAZ2DhpCwAA==",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-016.webp",
                "full": "/images/projects/project-1/full/img-016.webp",
                "thumb": "/images/projects/project-1/thumb/img-016.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoKAA0ABUB8JagCdADWkr8wAP7O5lR9btR0lJRJujszHAx5WxV88Zrn/x0wX3cWY9fr4AAA",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-017.webp",
                "full": "/images/projects/project-1/full/img-017.webp",
                "thumb": "/images/projects/project-1/thumb/img-017.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADwAQCdASoKAA0ABUB8JYwCdAEQ+dsVw8AA/meDMYL923E2t+tCwlrz//o4AA==",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-018.webp",
                "full": "/images/projects/project-1/full/img-018.webp",
                "thumb": "/images/projects/project-1/thumb/img-018.webp",
                "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoKAA0ABUB8JZACdADND442DEgA8TnPHl6/VdYWa8oX/2ph4hGO65Nf/CjVUndpuBZrYm7BPdCg/CcKTngYAAAA",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-019.webp",
                "full": "/images/projects/project-1/full/img-019.webp",
                "thumb": "/images/projects/project-1/thumb/img-019.webp",
                "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoKAAgABUB8JQBdgBuVLrZfIAD+yVv9skZbGz6neOAs5UoEvlFZ6D8KQGgAAA==",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-020.webp",
                "full": "/images/projects/project-1/full/img-020.webp",
                "thumb": "/images/projects/project-1/thumb/img-020.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoKAA0ABUB8JQBdgBjSyPxnAADztDT5o+CwV2wyX0KeFI8e+VT2M3uFxHCNhrbbiEr9eYeAAAA=",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-021.webp",
                "full": "/images/projects/project-1/full/img-021.webp",
                "thumb": "/images/projects/project-1/thumb/img-021.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAABwAQCdASoKAAgABUB8JZQAAk3g6AD8plj9GowWxFDwuEb5hAweHW12QAA=",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-022.webp",
                "full": "/images/projects/project-1/full/img-022.webp",
                "thumb": "/images/projects/project-1/thumb/img-022.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAADQAQCdASoKAAgABUB8JZQCdAD8K6TSQADb9WGBnXmPlWbu121yY5481AA=",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-023.webp",
                "full": "/images/projects/project-1/full/img-023.webp",
                "thumb": "/images/projects/project-1/thumb/img-023.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACQAQCdASoKAAgABUB8JYwCdAB/TAAAzIqDIvrbvSsd55ayaLZI+KJ7U6NAAA==",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-024.webp",
                "full": "/images/projects/project-1/full/img-024.webp",
                "thumb": "/images/projects/project-1/thumb/img-024.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAACQAQCdASoKAAgABUB8JZQAApz7sAAA/iWGJ/WSedtlzZXCAAA=",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-025.webp",
                "full": "/images/projects/project-1/full/img-025.webp",
                "thumb": "/images/projects/project-1/thumb/img-025.webp",
                "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACQAQCdASoKAA0ABUB8JYgCdADXGAAA+K+neJGRRjvpM/wtW7IuYoI+NoHsgDNrKQAAAA==",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-026.webp",
                "full": "/images/projects/project-1/full/img-026.webp",
                "thumb": "/images/projects/project-1/thumb/img-026.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoKAA0ABUB8JQBOgCHIMuybAADb8WRIK/OKgY4hNaHiUhkF7dwxl8gl07oxJXEEAAA=",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-027.webp",
                "full": "/images/projects/project-1/full/img-027.webp",
                "thumb": "/images/projects/project-1/thumb/img-027.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoKAA0ABUB8JQBOgBt9nUR8AAD3LGvj6GryVyOzm6e8cnGGtpviSur+h/3dPQAA",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-028.webp",
                "full": "/images/projects/project-1/full/img-028.webp",
                "thumb": "/images/projects/project-1/thumb/img-028.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACwAQCdASoKAAgABUB8JQBOgB6rDgQAAM4fSBaI+3tW2XtzpY9Sqt7HtvYAAA==",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-029.webp",
                "full": "/images/projects/project-1/full/img-029.webp",
                "thumb": "/images/projects/project-1/thumb/img-029.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACwAQCdASoKAA0ABUB8JQBOgCIfbjXQAN43Z21iHsiM7rJkzpfyWvQlyY1pAwAA",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-030.webp",
                "full": "/images/projects/project-1/full/img-030.webp",
                "thumb": "/images/projects/project-1/thumb/img-030.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoKAAgABUB8JQBOgCPqQzoNAAD9dnBk2DW7Qrd2qcMW7RbzjsfJDNplJ5yJAEgA",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-031.webp",
                "full": "/images/projects/project-1/full/img-031.webp",
                "thumb": "/images/projects/project-1/thumb/img-031.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADwAQCdASoKAAgABUB8JQBOgB6vjqnPlwAA+Fsf93SOxz2HqIV2Qb2Yzm95V66AAAA=",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-032.webp",
                "full": "/images/projects/project-1/full/img-032.webp",
                "thumb": "/images/projects/project-1/thumb/img-032.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADwAQCdASoKAAgABUB8JYgCdAE2qURZQAAA4PtFjUlRINPSoypDhLrse1wAAA==",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-033.webp",
                "full": "/images/projects/project-1/full/img-033.webp",
                "thumb": "/images/projects/project-1/thumb/img-033.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADwAQCdASoKAA0ABUB8JQBOgBu1Af3n5AAA/Pxk38jmWO5+atW0rGvOWKmjiXvSXjF7otRAAAA=",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-034.webp",
                "full": "/images/projects/project-1/full/img-034.webp",
                "thumb": "/images/projects/project-1/thumb/img-034.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACwAQCdASoKAA0ABUB8JYwCdAD0p4AAAP4/mqYF8g2i+A2bInWiyOAe+0Ism3AA",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-035.webp",
                "full": "/images/projects/project-1/full/img-035.webp",
                "thumb": "/images/projects/project-1/thumb/img-035.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACwAQCdASoKAAgABUB8JQBOgBuy73ngAPhhI4jngtQlYOXgdv8jfm21bPjB5AAA",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-036.webp",
                "full": "/images/projects/project-1/full/img-036.webp",
                "thumb": "/images/projects/project-1/thumb/img-036.webp",
                "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoKAA0ABUB8JQBWACLJ7S1uAAD2dTQsbvWoo/gJ/yGuZgH6Q6QHiYHYFMB6S25aVaFYrGH3+0rk0LF6Zt8uoOXAAAA=",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-037.webp",
                "full": "/images/projects/project-1/full/img-037.webp",
                "thumb": "/images/projects/project-1/thumb/img-037.webp",
                "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoKAAgABUB8JZwAAu0T0Mh2gAD4YN46hp3XB18/TnmIzM/wQAJTggvGJcAAAA==",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-038.webp",
                "full": "/images/projects/project-1/full/img-038.webp",
                "thumb": "/images/projects/project-1/thumb/img-038.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAADQAQCdASoKAA0ABUB8JYwCw7D0Mll5IAD+wAy1pDgM8hg0TIocdrcYAAA=",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-039.webp",
                "full": "/images/projects/project-1/full/img-039.webp",
                "thumb": "/images/projects/project-1/thumb/img-039.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACQAQCdASoKAAgABUB8JQAAU4rek+AA+vIisQ0P0Np0FL2u/BO7FaewhwAAAA==",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-040.webp",
                "full": "/images/projects/project-1/full/img-040.webp",
                "thumb": "/images/projects/project-1/thumb/img-040.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoKAA0ABUB8JZACdAEOONErgAD+zdCP+Sk2x773Dml+s/k7rZKJq6wNA+9h+lI4sjpNjmgAAAA=",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-041.webp",
                "full": "/images/projects/project-1/full/img-041.webp",
                "thumb": "/images/projects/project-1/thumb/img-041.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACwAQCdASoKAAgABUB8JZQAAtzg1qd4ANzsV4epWXLUlfGGIoXJXagQ3OXAgAAA",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-042.webp",
                "full": "/images/projects/project-1/full/img-042.webp",
                "thumb": "/images/projects/project-1/thumb/img-042.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoKAA0ABUB8JYwCdAEPEOg8AAD2nBA/R2jRkjXXN46itDMOFmltXEVoOHFmhdScwUqgAA==",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-043.webp",
                "full": "/images/projects/project-1/full/img-043.webp",
                "thumb": "/images/projects/project-1/thumb/img-043.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAQCdASoKAAgABUB8JYgCdAEDfCn4e4AA3k2h9BtLF3E/oj3GVS8aKOV6zZZBXDggtEILNEgAAA==",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-044.webp",
                "full": "/images/projects/project-1/full/img-044.webp",
                "thumb": "/images/projects/project-1/thumb/img-044.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoKAAgABUB8JbAAAl0WFB9sAAD+qNvACeqDnY2HZt+2CFo+d9ugygNWOcRd1Ye4AAA=",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-045.webp",
                "full": "/images/projects/project-1/full/img-045.webp",
                "thumb": "/images/projects/project-1/thumb/img-045.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAACwAQCdASoKAAgABUB8JQAAS7e6XoXAAP5U5Mg1bInHTMvlShTDgAAA",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-046.webp",
                "full": "/images/projects/project-1/full/img-046.webp",
                "thumb": "/images/projects/project-1/thumb/img-046.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoKAAgABUB8JQBOgBulEQ8CyADLO7dLS8ve348qtO5oDCZo6nPm1iN162p0esCAaH7MAAAA",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-047.webp",
                "full": "/images/projects/project-1/full/img-047.webp",
                "thumb": "/images/projects/project-1/thumb/img-047.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAQCdASoKAAgABUB8JYwCdADdQQBPrAAA/tzL8xPvPmnWwcwYH1Sdqkojz41vzzyLrIAA",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-048.webp",
                "full": "/images/projects/project-1/full/img-048.webp",
                "thumb": "/images/projects/project-1/thumb/img-048.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoKAA0ABUB8JZQAAuaerViPAgAA/I5HA9NzqBhklF3i0uWG1+ImPhi2B0sIodrKscef4AAA",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-049.webp",
                "full": "/images/projects/project-1/full/img-049.webp",
                "thumb": "/images/projects/project-1/thumb/img-049.webp",
                "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoKAA0ABUB8JYwCsADDq6O6oQAA+VtpJVAZUhpj0j0I7IQX6GaRJD4n2HD1i3awgb2/pfNwlivWLFNMAAA=",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-050.webp",
                "full": "/images/projects/project-1/full/img-050.webp",
                "thumb": "/images/projects/project-1/thumb/img-050.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoKAAgABUB8JYwCdADhkuaSYADOCzwtNZnpEG1xcoREXsscKIFcq+4AAAA=",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-051.webp",
                "full": "/images/projects/project-1/full/img-051.webp",
                "thumb": "/images/projects/project-1/thumb/img-051.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACwAQCdASoKAAgABUB8JZQAAlr90GTwAP2+u6Km4qKs0pBHeVvXyhw9K46biKAA",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-052.webp",
                "full": "/images/projects/project-1/full/img-052.webp",
                "thumb": "/images/projects/project-1/thumb/img-052.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoKAA0ABUB8JbACdAEUTMndWAAA/bXjh5TaYo2jWkA4uxW57ZYr4llmi0ZS4FJiZFqSbdUebzWAAA==",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-053.webp",
                "full": "/images/projects/project-1/full/img-053.webp",
                "thumb": "/images/projects/project-1/thumb/img-053.webp",
                "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAABwAwCdASoKABIAPzmGuVOvKSWisAgB4CcJYwC7ABs3AEMP12QA+pfUUJVlPkFYD4I9bsbQ72v50JqFs1J2gl6h6JW1QnUvwJisBK2ATgAAAA==",
                "width": 900,
                "height": 1600
          },
          {
                "filename": "img-054.webp",
                "full": "/images/projects/project-1/full/img-054.webp",
                "thumb": "/images/projects/project-1/thumb/img-054.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoKAAgABUB8JZACdADZoVZ2gAD+flC2sCBlL3rqLGU+Gb9GUXDhg+64YrOZe/xaLUB5ZmSAAAA=",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-055.webp",
                "full": "/images/projects/project-1/full/img-055.webp",
                "thumb": "/images/projects/project-1/thumb/img-055.webp",
                "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoKAA0ABUB8JYwAAv94iI5lAAD0RMt/pU9QV20/0ZtnvoTPyfphYr4EtQAAAA==",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-056.webp",
                "full": "/images/projects/project-1/full/img-056.webp",
                "thumb": "/images/projects/project-1/thumb/img-056.webp",
                "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADwAQCdASoKAAgABUB8JYwCdAEWIRkqYQAA+Uicn7eoy/yO6+aL8kz6FfNtiEOMTdKoAA==",
                "width": 1600,
                "height": 1200
          }
    ],
    videos: [
          {
                "filename": "video-01.mp4",
                "src": "/videos/project-1/video-01.mp4"
          },
          {
                "filename": "video-02.mp4",
                "src": "/videos/project-1/video-02.mp4"
          },
          {
                "filename": "video-03.mp4",
                "src": "/videos/project-1/video-03.mp4"
          },
          {
                "filename": "video-04.mp4",
                "src": "/videos/project-1/video-04.mp4"
          },
          {
                "filename": "video-05.mp4",
                "src": "/videos/project-1/video-05.mp4"
          },
          {
                "filename": "video-06.mp4",
                "src": "/videos/project-1/video-06.mp4"
          },
          {
                "filename": "video-07.mp4",
                "src": "/videos/project-1/video-07.mp4"
          },
          {
                "filename": "video-08.mp4",
                "src": "/videos/project-1/video-08.mp4"
          },
          {
                "filename": "video-09.mp4",
                "src": "/videos/project-1/video-09.mp4"
          },
          {
                "filename": "video-10.mp4",
                "src": "/videos/project-1/video-10.mp4"
          },
          {
                "filename": "video-11.mp4",
                "src": "/videos/project-1/video-11.mp4"
          },
          {
                "filename": "video-12.mp4",
                "src": "/videos/project-1/video-12.mp4"
          }
    ],
  },
  {
    id: "project-2",
    images: [
          {
                "filename": "img-001.webp",
                "full": "/images/projects/project-2/full/img-001.webp",
                "thumb": "/images/projects/project-2/thumb/img-001.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoKAA0ABUB8JQAAXvDrhsMvSAD8DTCKnJjP9GDUujxhFmRyAfY2DdG+Q6l3Tkatv6HcqnAA",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-002.webp",
                "full": "/images/projects/project-2/full/img-002.webp",
                "thumb": "/images/projects/project-2/thumb/img-002.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAQCdASoKAA0ABUB8JYwAAtzNPEJwizgA/iTytDwlSFsxoPIhHzeZ1eaZ4SxdgOG5kAAA",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-003.webp",
                "full": "/images/projects/project-2/full/img-003.webp",
                "thumb": "/images/projects/project-2/thumb/img-003.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACQAQCdASoKAA0ABUB8JZQAApxCD4AA/sv3i6jQBEsyDVP7gcixV+Lguf1G+5kAAAA=",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-004.webp",
                "full": "/images/projects/project-2/full/img-004.webp",
                "thumb": "/images/projects/project-2/thumb/img-004.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoKAA0ABUB8JYwAApzX4OBIAP54GNJu7RFgWrbMpAPlAySasidTygeQAAA=",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-005.webp",
                "full": "/images/projects/project-2/full/img-005.webp",
                "thumb": "/images/projects/project-2/thumb/img-005.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoKAA0ABUB8JZwAAknx6d4AAPsXkVhYmnnzzbxbvnKIoS9p1Utcqr9nzIVYQAAA",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-006.webp",
                "full": "/images/projects/project-2/full/img-006.webp",
                "thumb": "/images/projects/project-2/thumb/img-006.webp",
                "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoKAA0ABUB8JZQAAueLOnMVwAD+g6Fdtz2RDVf/bYPzfILevS3czXIkdNqAAA==",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-007.webp",
                "full": "/images/projects/project-2/full/img-007.webp",
                "thumb": "/images/projects/project-2/thumb/img-007.webp",
                "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACwAQCdASoKAA0ABUB8JZwAAv52V2+AAP4RuRUvqmYm9cPOwV/CPXzNTpedIrRR5VbYAA==",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-008.webp",
                "full": "/images/projects/project-2/full/img-008.webp",
                "thumb": "/images/projects/project-2/thumb/img-008.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAACwAQCdASoKAAgABUB8JZwAAbiDWosAAJT0XTw6bv3iCflcMPk+AAAA",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-009.webp",
                "full": "/images/projects/project-2/full/img-009.webp",
                "thumb": "/images/projects/project-2/thumb/img-009.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACQAQCdASoKAA0ABUB8JZwAAkj8xkAAziNRt9K8c44YfWwmwIPJxyWRUScfgAAA",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-010.webp",
                "full": "/images/projects/project-2/full/img-010.webp",
                "thumb": "/images/projects/project-2/thumb/img-010.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoKAA0ABUB8JZgCdADznw/vAAD+WiYrhg9e0oG8DJzucKtudmrzMJ9O00sxMbGAWMAAAA==",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-011.webp",
                "full": "/images/projects/project-2/full/img-011.webp",
                "thumb": "/images/projects/project-2/thumb/img-011.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoKAA0ABUB8JagCw7DZLKxhAADMY3pSxRBRTDtDVY5MthNvXw/i1M7W93RvTpw+svwAAA==",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-012.webp",
                "full": "/images/projects/project-2/full/img-012.webp",
                "thumb": "/images/projects/project-2/thumb/img-012.webp",
                "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAABQAQCdASoKAAgABUB8JZQAAkuAAP6p+0DEcsl6ju8EZ0KntfB2OlLgo5tUv4HNCD34AA==",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-013.webp",
                "full": "/images/projects/project-2/full/img-013.webp",
                "thumb": "/images/projects/project-2/thumb/img-013.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADwAQCdASoKAAgABUB8JZQC7AEQCtUTYwAA/phcYZDkVBGclYTj6lb1l9QAAA==",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-014.webp",
                "full": "/images/projects/project-2/full/img-014.webp",
                "thumb": "/images/projects/project-2/thumb/img-014.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjIAAABXRUJQVlA4ICYAAABwAQCdASoKAAgABUB8JZQAAuYegAD+1PmrSKa1zg+yaV2xTUA4AA==",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-015.webp",
                "full": "/images/projects/project-2/full/img-015.webp",
                "thumb": "/images/projects/project-2/thumb/img-015.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjIAAABXRUJQVlA4ICYAAADQAQCdASoKAAgABUB8JZwAAp3UAKt6AAD+xRRyb/3QOiz+aYAAAA==",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-016.webp",
                "full": "/images/projects/project-2/full/img-016.webp",
                "thumb": "/images/projects/project-2/thumb/img-016.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAQCdASoKAA0ABUB8JYwCdADQ5uGVkwAA/tCNLXT3QSiB1uHxbKorQCvXkyLY3ACyAAAA",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-017.webp",
                "full": "/images/projects/project-2/full/img-017.webp",
                "thumb": "/images/projects/project-2/thumb/img-017.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoKAAgABUB8JZQAAiV2iJMAAP6sBpVi2FOZlbALodMfOUd28+lFN9TrutQlG5kAAAA=",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-018.webp",
                "full": "/images/projects/project-2/full/img-018.webp",
                "thumb": "/images/projects/project-2/thumb/img-018.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADwAQCdASoKAAgABUB8JZQC7AD5g7+zfgAA/jf1ppgPRv9y5DG29bPUJAx6gplAAAA=",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-019.webp",
                "full": "/images/projects/project-2/full/img-019.webp",
                "thumb": "/images/projects/project-2/thumb/img-019.webp",
                "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAwCdASoKABIAPzmGuVOvKSWisAgB4CcJZQCsACKcVAqKirfwAAD+ABh/jSdp43Ec0Q2FQ66qHJs+MSRtVlkyluf1wpQ8dpWgFn3Btwe3DCAA",
                "width": 900,
                "height": 1600
          },
          {
                "filename": "img-020.webp",
                "full": "/images/projects/project-2/full/img-020.webp",
                "thumb": "/images/projects/project-2/thumb/img-020.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADwAQCdASoKAA0ABUB8JYwCdAEKuOW3/AAA/prO2j6Dd1/jjXD4YBoBwMFxYkYAQAA=",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-021.webp",
                "full": "/images/projects/project-2/full/img-021.webp",
                "thumb": "/images/projects/project-2/thumb/img-021.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADwAQCdASoKAA0ABUB8JaACdAD0UMre8gAA/I60vhZE24F9/r6CJHVA8nYYaZW84xFucL7AAAA=",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-022.webp",
                "full": "/images/projects/project-2/full/img-022.webp",
                "thumb": "/images/projects/project-2/thumb/img-022.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoKAAgABUB8JYwCsAEec58SAAD2RBmtLSC6pgvswf2n+iyCCToCh5HgAAA=",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-023.webp",
                "full": "/images/projects/project-2/full/img-023.webp",
                "thumb": "/images/projects/project-2/thumb/img-023.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADwAQCdASoKAA0ABUB8JYwCdAD8Jv9jaAAA/IQFERWxdS1JWs3mve74FgLIViBpAAA=",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-024.webp",
                "full": "/images/projects/project-2/full/img-024.webp",
                "thumb": "/images/projects/project-2/thumb/img-024.webp",
                "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAABwAwCdASoKABIAPzmGuVOvKSWisAgB4CcJZwDG9BuFvRKsnmAAysSw9IXTpSPG6Pyf0RcsG+dFa76t3p6qaLkVbNcS4FRsgAA=",
                "width": 900,
                "height": 1600
          },
          {
                "filename": "img-025.webp",
                "full": "/images/projects/project-2/full/img-025.webp",
                "thumb": "/images/projects/project-2/thumb/img-025.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoKAA0ABUB8JYwC7AD7FqWcAADh22TF7XT2/CQn46GjsmEk52CYhtAI2WIx6kU9IZydVQAA",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-026.webp",
                "full": "/images/projects/project-2/full/img-026.webp",
                "thumb": "/images/projects/project-2/thumb/img-026.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADQAQCdASoKAA0ABUB8JYwC7ADb0axA4AD+aBM/dtXYRXvi7ruFp2hlioAAAA==",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-027.webp",
                "full": "/images/projects/project-2/full/img-027.webp",
                "thumb": "/images/projects/project-2/thumb/img-027.webp",
                "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoKAAgABUB8JQBOgBuUPSXaAAD9/N/UPecIzFx7mnn6KyujKstHyfo+iMAAAA==",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-028.webp",
                "full": "/images/projects/project-2/full/img-028.webp",
                "thumb": "/images/projects/project-2/thumb/img-028.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADwAQCdASoKAAgABUB8JYgCdAELzssVWwAA+OShxnLad7lWUx2/h4ezprQN2ZskIY3P3zMAAAA=",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-029.webp",
                "full": "/images/projects/project-2/full/img-029.webp",
                "thumb": "/images/projects/project-2/thumb/img-029.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoKAA0ABUB8JZQC7AEO4dbcH6gA/obTfulR19dxOgp2Da5YAQtxREPzZovEV4LM2IzNBSf4gAA=",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-030.webp",
                "full": "/images/projects/project-2/full/img-030.webp",
                "thumb": "/images/projects/project-2/thumb/img-030.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAAAQAgCdASoKAA0ABUB8JZwC7ADdYe449+hgAP1S9WEKLF+OsqTlq1ww7rPOV0CoFE8FJ0UdI5HtzAAA",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-031.webp",
                "full": "/images/projects/project-2/full/img-031.webp",
                "thumb": "/images/projects/project-2/thumb/img-031.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoKAAgABUB8JQBfnCL2ok7wAAD8jsicaFoAA7iBAuMhU9VeG4B7O81EgM0PxwAA",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-032.webp",
                "full": "/images/projects/project-2/full/img-032.webp",
                "thumb": "/images/projects/project-2/thumb/img-032.webp",
                "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAQCdASoKAAgABUB8JbACdADYC6gAAN5KIeRkB73mp1myXxMdBV4KCOJiHbrIQ/Hhpd3nL/UVzwTgELM8dHe59yAAAA==",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-033.webp",
                "full": "/images/projects/project-2/full/img-033.webp",
                "thumb": "/images/projects/project-2/thumb/img-033.webp",
                "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoKAA0ABUB8JZQC7AELTdVGAAD9mfkLtD1Y9NnzbvILJyl71WTqErmBtQAAAA==",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-034.webp",
                "full": "/images/projects/project-2/full/img-034.webp",
                "thumb": "/images/projects/project-2/thumb/img-034.webp",
                "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAAAQAgCdASoKAA0ABUB8JQBOgCHQWlqDRVIAAP7Y5jupdapn2gu26As6TDqgu1oYYAAAAA==",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-035.webp",
                "full": "/images/projects/project-2/full/img-035.webp",
                "thumb": "/images/projects/project-2/thumb/img-035.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACwAQCdASoKAAgABUB8JYwC7ADbUj4AAOAdAaBIuOQpQ7VPrDbSgi+MBUAAAA==",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-036.webp",
                "full": "/images/projects/project-2/full/img-036.webp",
                "thumb": "/images/projects/project-2/thumb/img-036.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoKAAgABUB8JbACdADa+MQAAPDjS1JJDQ0qcEw/uYvDnWIl3hj3rHtooAA=",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-037.webp",
                "full": "/images/projects/project-2/full/img-037.webp",
                "thumb": "/images/projects/project-2/thumb/img-037.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoKAAgABUB8JZACdAD1V3CKUADeNAAspls1beiVyBoLh6g25tCqzLwA",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-038.webp",
                "full": "/images/projects/project-2/full/img-038.webp",
                "thumb": "/images/projects/project-2/thumb/img-038.webp",
                "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoKAA0ABUB8JQAATQrNs18sAAD+6D8b4eB1OWxPN1uc1Nz91z4FY2pgWCaNyryliXxoXJqfd7/wvlkymNQAAA==",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-039.webp",
                "full": "/images/projects/project-2/full/img-039.webp",
                "thumb": "/images/projects/project-2/thumb/img-039.webp",
                "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoKAA0ABUB8JbACdADhccAbtlcAAPY9nLU00+06N6MSs6Agxyq8evyeMjjf4mnbk6a0h9A+f0+Midd2C5e53SwYYSuHYyPl7SBRcAAA",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-040.webp",
                "full": "/images/projects/project-2/full/img-040.webp",
                "thumb": "/images/projects/project-2/thumb/img-040.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACQAQCdASoKAAgABUB8JQBOgBt6oAAA9Q4NIH98oanNWZCeFKNJLdT3nsEAAA==",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-041.webp",
                "full": "/images/projects/project-2/full/img-041.webp",
                "thumb": "/images/projects/project-2/thumb/img-041.webp",
                "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoKAA0ABUB8JYwC7ADbYuvK0ADh/aFZPGlb4n7tHVQzLRMin4sqSGXOyCDr3JjTyLBCIbdVBlJt/b/fmIAAAA==",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-042.webp",
                "full": "/images/projects/project-2/full/img-042.webp",
                "thumb": "/images/projects/project-2/thumb/img-042.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAABwAQCdASoKAAgABUB8JZwAAtw8AADNyJxg814h3stbxib+QRl8cGCcDShAAA==",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-043.webp",
                "full": "/images/projects/project-2/full/img-043.webp",
                "thumb": "/images/projects/project-2/thumb/img-043.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoKAA0ABUB8JQBOgBszlaAAAP61ZqET/Y6Ysh2IX54SjZtih6TAZJtKCsSDZss9cg+QAAAA",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-044.webp",
                "full": "/images/projects/project-2/full/img-044.webp",
                "thumb": "/images/projects/project-2/thumb/img-044.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAwAgCdASoKAA0ABUB8JYwCdAEYGWeeBDjAAAD3QdHK+1Kpb3TAlLgm1WeATrrHCM1Z6QS1l94blZ8sKZ/RbAAA",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-045.webp",
                "full": "/images/projects/project-2/full/img-045.webp",
                "thumb": "/images/projects/project-2/thumb/img-045.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACQAQCdASoKAA0ABUB8JZQAAuTuDwAA/owfjrbX6WE/TDIB9Rg2nHE9aWd+AAAA",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-046.webp",
                "full": "/images/projects/project-2/full/img-046.webp",
                "thumb": "/images/projects/project-2/thumb/img-046.webp",
                "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADwAwCdASoKABIAPzmEuVOvKKWisAgB4CcJYgC7ABrJ/swITfHyTPwAAPVUlCRYzXIji6khGMMdwnYf/a2FnVsYn0e+4MT4ch9zwaBMTmELG8iTe/zheYLwCU3o/qmjJV8LkQAA",
                "width": 900,
                "height": 1600
          },
          {
                "filename": "img-047.webp",
                "full": "/images/projects/project-2/full/img-047.webp",
                "thumb": "/images/projects/project-2/thumb/img-047.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADwAQCdASoKAAgABUB8JYgCdAELS5YBWAAA99wJ3oa3t3ZP4H+Ia0Do9RMMflIAAAA=",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-048.webp",
                "full": "/images/projects/project-2/full/img-048.webp",
                "thumb": "/images/projects/project-2/thumb/img-048.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACwAQCdASoKAAgABUB8JZQAAlreiVsAAPveAvf1l53EGONjFVjGheAFy9NaAHAA",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-049.webp",
                "full": "/images/projects/project-2/full/img-049.webp",
                "thumb": "/images/projects/project-2/thumb/img-049.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACwAQCdASoKAA0ABUB8JQAAUvfBT83wAP6fBHMwm2SPXO/wY3HHcovzdvG3Wc3gsyx+fud72A4AAA==",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-050.webp",
                "full": "/images/projects/project-2/full/img-050.webp",
                "thumb": "/images/projects/project-2/thumb/img-050.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoKAA0ABUB8JZgAAl1htcEZAAD+nwl+R03lqGn9rxySliryQpxBUgyA/4Bg2DL0cnuz7zycXt4AAA==",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-051.webp",
                "full": "/images/projects/project-2/full/img-051.webp",
                "thumb": "/images/projects/project-2/thumb/img-051.webp",
                "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACQAQCdASoKAA0ABUB8JZQC7ADYXAAA4nER4ILZWfvDRwUcA9W8Qb/p0JNoUNUl9NAAAA==",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-052.webp",
                "full": "/images/projects/project-2/full/img-052.webp",
                "thumb": "/images/projects/project-2/thumb/img-052.webp",
                "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoKAA0ABUB8JQBOkERic6yz9twAAP6U/ejajuYZFkAY70KH6KWLUOOMTdSxBkTcHMkOG114LD8bChOQzc17gUbGr2WAAA==",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-053.webp",
                "full": "/images/projects/project-2/full/img-053.webp",
                "thumb": "/images/projects/project-2/thumb/img-053.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoKAA0ABUB8JZQAAl3CVzJqiqAA/NU231ZHev+hmur9TMBIlFNBWaFFoFQ4I6Cd9Twp/FBlkQLu2lIA",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-054.webp",
                "full": "/images/projects/project-2/full/img-054.webp",
                "thumb": "/images/projects/project-2/thumb/img-054.webp",
                "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAQCdASoKAA0ABUB8JQAAYoBFhhuAAP7VqmwJp0jHWSET7x9fp4bLEk2TnpNGAYWMVIYo0EMSBnnunxQkoEXw9yobAAAA",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-055.webp",
                "full": "/images/projects/project-2/full/img-055.webp",
                "thumb": "/images/projects/project-2/thumb/img-055.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoKAAgABUB8JYwC7ADZt3fAAPsW5ZEj741NZ/8CaHT21JW3MussC2fjwAA=",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-056.webp",
                "full": "/images/projects/project-2/full/img-056.webp",
                "thumb": "/images/projects/project-2/thumb/img-056.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAAAQAgCdASoKAA0ABUB8JYwC7ADdLNHEn6UAAOJ1yvk5gD69xnQzBonFVtBYX2Y/GgSsyKBeDT+yAAAA",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-057.webp",
                "full": "/images/projects/project-2/full/img-057.webp",
                "thumb": "/images/projects/project-2/thumb/img-057.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoKAA0ABUB8JYwCw7DdYfnS2AD9dQbMcOXp+Wu8tjDkTNtfPdF81IKrCHzZBYAA",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-058.webp",
                "full": "/images/projects/project-2/full/img-058.webp",
                "thumb": "/images/projects/project-2/thumb/img-058.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoKAAgABUB8JYwCdACkIpZMAAD+I69fNJVWK8v57kMBr0ZhTF4NusgA",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-059.webp",
                "full": "/images/projects/project-2/full/img-059.webp",
                "thumb": "/images/projects/project-2/thumb/img-059.webp",
                "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACwAQCdASoKAAgABUB8JQBOgBudIObQAMweYw+l7xJaIHQFJ3RmhmwwIibqJavbTIAAAA==",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-060.webp",
                "full": "/images/projects/project-2/full/img-060.webp",
                "thumb": "/images/projects/project-2/thumb/img-060.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACQAQCdASoKAA0ABUB8JYgCdADYTEAA9EZUEshvopgPJgPtiChLPeMtEB1QntJEJMzbG5s3vNmNmskc4HWemwAA",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-061.webp",
                "full": "/images/projects/project-2/full/img-061.webp",
                "thumb": "/images/projects/project-2/thumb/img-061.webp",
                "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADwAQCdASoKAA0ABUB8JQBOgB6UitrTMAAA/iSkdD86Ka9V6vHdFV+68iwsfhWj3VgAAA==",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-062.webp",
                "full": "/images/projects/project-2/full/img-062.webp",
                "thumb": "/images/projects/project-2/thumb/img-062.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACwAQCdASoKAAgABUB8JYwAAvdqxFuoAPyKX4OpsMIR0FvyvrslnNKs2d3VsAAA",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-063.webp",
                "full": "/images/projects/project-2/full/img-063.webp",
                "thumb": "/images/projects/project-2/thumb/img-063.webp",
                "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoKAA0ABUB8JYwCw7DcqYM1hAAA+ku0fK4daUjS9wlhzQ5zm6bA4890yWj8K1zSJeW9S2S/3j1eSXAAAAA=",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-064.webp",
                "full": "/images/projects/project-2/full/img-064.webp",
                "thumb": "/images/projects/project-2/thumb/img-064.webp",
                "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAQCdASoKAA0ABUB8JQAAXaKu8aAAAPa17TdWHwX6CGhx3QsTl+jO+l8lufi1GCZhClXtTheBLzRfAL0DnpfxwAA=",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-065.webp",
                "full": "/images/projects/project-2/full/img-065.webp",
                "thumb": "/images/projects/project-2/thumb/img-065.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoKAA0ABUB8JZQCdAD0NpfMKIAA999O2rvUssaT1ffYemSqHP2wDpkyIlN1wWOEY7rowAAA",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-066.webp",
                "full": "/images/projects/project-2/full/img-066.webp",
                "thumb": "/images/projects/project-2/thumb/img-066.webp",
                "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADwAQCdASoKAAgABUB8JZQC7AEWzGhXcFAA/NDyLZxzAWtA4cIbUHa3+czKB9lotQAAAA==",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-067.webp",
                "full": "/images/projects/project-2/full/img-067.webp",
                "thumb": "/images/projects/project-2/thumb/img-067.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAAAQAgCdASoKAAgABUB8JbACdAEQzT5Ua5wAAP6DmGC5zrlhJhHlKAvtUcxhtIJ8KboOtmPgOiI6RAAA",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-068.webp",
                "full": "/images/projects/project-2/full/img-068.webp",
                "thumb": "/images/projects/project-2/thumb/img-068.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACQAQCdASoKAAgABUB8JQBOgBswZDAA9kQ0f8Cwu06yjjkMin3/qOy9VXJlzt/AvCIJCjGFaA0AAA==",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-069.webp",
                "full": "/images/projects/project-2/full/img-069.webp",
                "thumb": "/images/projects/project-2/thumb/img-069.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoKAA0ABUB8JZACdAEDe+3AYAAA/Nbyp48SKP1VOPh2nvBfMX/C8FO2nyGUPn/QnYx53PwBOkUAAA==",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-070.webp",
                "full": "/images/projects/project-2/full/img-070.webp",
                "thumb": "/images/projects/project-2/thumb/img-070.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAACwAQCdASoKAAgABUB8JZQAAvabPFzwAPKmxzHzpRm9WeGqbMUyQoAA",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-071.webp",
                "full": "/images/projects/project-2/full/img-071.webp",
                "thumb": "/images/projects/project-2/thumb/img-071.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACQAQCdASoKAA0ABUB8JQBOgBs1VMgA/fBf6icpPDwciq7RRDA84aaObVsBaebIzdFOOH0sAEOipr0oAAA=",
                "width": 1200,
                "height": 1600
          },
          {
                "filename": "img-072.webp",
                "full": "/images/projects/project-2/full/img-072.webp",
                "thumb": "/images/projects/project-2/thumb/img-072.webp",
                "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoKAAgABUB8JZQC7AEVwiwIAAD+W/0G0bDjT7CbyScsy1plVKb+ki24AAA=",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-073.webp",
                "full": "/images/projects/project-2/full/img-073.webp",
                "thumb": "/images/projects/project-2/thumb/img-073.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADwAQCdASoKAAgABUB8JQBOgCFw5D03fFgA/LGNi/+tzYSbs9SGtM5NTTKYiAK9lcaCG4JgAAA=",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-074.webp",
                "full": "/images/projects/project-2/full/img-074.webp",
                "thumb": "/images/projects/project-2/thumb/img-074.webp",
                "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAAAQAgCdASoKAAgABUB8JYgCdAEYGRno9k0AAPY9iP3akml+AxgvRyGjenETnRuXcez6nantQqcoP/6AAAA=",
                "width": 1600,
                "height": 1200
          },
          {
                "filename": "img-075.webp",
                "full": "/images/projects/project-2/full/img-075.webp",
                "thumb": "/images/projects/project-2/thumb/img-075.webp",
                "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoKAA0ABUB8JZACdADdbGgcNKBAAM44eiM3OTIdVeUZbA7JB+I58bnA55qMK00lANsOyM+CwmmM0i/uawBWu2SWAFEAAA==",
                "width": 1200,
                "height": 1600
          }
    ],
    videos: [
          {
                "filename": "video-01.mp4",
                "src": "/videos/project-2/video-01.mp4"
          },
          {
                "filename": "video-02.mp4",
                "src": "/videos/project-2/video-02.mp4"
          },
          {
                "filename": "video-03.mp4",
                "src": "/videos/project-2/video-03.mp4"
          },
          {
                "filename": "video-04.mp4",
                "src": "/videos/project-2/video-04.mp4"
          },
          {
                "filename": "video-05.mp4",
                "src": "/videos/project-2/video-05.mp4"
          },
          {
                "filename": "video-06.mp4",
                "src": "/videos/project-2/video-06.mp4"
          },
          {
                "filename": "video-07.mp4",
                "src": "/videos/project-2/video-07.mp4"
          },
          {
                "filename": "video-08.mp4",
                "src": "/videos/project-2/video-08.mp4"
          },
          {
                "filename": "video-09.mp4",
                "src": "/videos/project-2/video-09.mp4"
          },
          {
                "filename": "video-10.mp4",
                "src": "/videos/project-2/video-10.mp4"
          }
    ],
  },
];

export const allImages: ProjectImage[] = projects.flatMap((p) => p.images);
export const allVideos: ProjectVideo[] = projects.flatMap((p) => p.videos);

export function getProjectById(id: string): Project | undefined {
  return projects.find((p) => p.id === id);
}
